apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Sleepr
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3

availabilityZones: ['us-east-1a', 'us-east-1b']